// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeFileByContent(arg1) {
  return window['go']['main']['App']['AnalyzeFileByContent'](arg1);
}

export function AnalyzeFileByPath(arg1) {
  return window['go']['main']['App']['AnalyzeFileByPath'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SummarizePayload(arg1) {
  return window['go']['main']['App']['SummarizePayload'](arg1);
}
