// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnalyzeFileByContent(arg1:models.AnalyzeByContentRequest):Promise<models.ScanResult>;

export function AnalyzeFileByPath(arg1:models.AnalyzeByPathRequest):Promise<models.ScanResult>;

export function GetHistory():Promise<Array<models.HistoryItem>>;

export function GetSettings():Promise<models.SettingsState>;

export function PickFile():Promise<string>;

export function SaveSettings(arg1:models.SaveSettingsRequest):Promise<models.SaveSettingsResponse>;

export function SummarizePayload(arg1:models.AISummaryRequest):Promise<string>;
